apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ivan-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        service: backend
    spec:
      containers:
      - name: ivan-backend
        image: phompang/ivan-backend:0.0.23
        resources:
          requests:
            memory: "24Mi"
            cpu: "10m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /test
            port: 3000