export const brand = ['Honda',
  'Isuzu',
  'Lexus',
  'Mazda',
  'Mitsubishi',
  'Nissan',
  'Toyota',
  'Subaru',
  'Hyundai',
  'Kia',
  'Volvo',
  'Koenigsegg',
  'Aston Martin',
  'Bentley',
  'Jaguar',
  'Land Rover',
  'McLaren',
  'Mini',
  'Rolls Royce']
